services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    depends_on:
      selenium:
        condition: service_started
      postgres:
        condition: service_healthy

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    depends_on:
      - api
    volumes:
      - ./src:/app/src

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: "2g"

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U movies -d movies_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
