services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - selenium

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file: .env
    depends_on:
      - api
    volumes:
      - ./src:/app/src

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: "2g"
